# .streamlit/config.toml

[theme]
primaryColor = "#4CAF50"             # Verde principal para light
backgroundColor = "#FFFFFF"          # Fundo da página light
secondaryBackgroundColor = "#F5F5F5" # Cards, sidebar e backgrounds secundários
textColor = "#333333"                # Texto padrão
font = "sans serif"


[server]
enableStaticServing = true

[client]
showSidebarNavigation = false