# .streamlit/config.toml

[theme]
primaryColor = "#8DC63F"             # Verde principal da Sicredi
backgroundColor = "#111111"          # Fundo escuro
secondaryBackgroundColor = "#393939" # Cards e fundos secundários
textColor = "#FFFFFF"                 # Texto branco
font = "sans serif"                   # Fonte padrão

[server]
enableStaticServing = true

[client]
showSidebarNavigation = false